Repository vercel/docs, pull requests merged in 2019-08, with the labels that each got.

#1073 Update Avatar Menu to match ZEIT website
  components/layout/header/avatar-popover-link.js
Labels: UI

#1072 [now-php] Move docs to separate repo
  lib/data/now-examples-api.json
  lib/data/now-examples.json
  pages/docs/api/v2/api-docs-mdx/endpoints/deployments.mdx
  pages/docs/v2/advanced/concepts/lambdas.mdx
  pages/docs/v2/advanced/configuration.mdx
  pages/docs/v2/serverless-functions/supported-languages.mdx
Labels: Category: Advanced, Category: Serverless Functions

#1096 Update version selector format
  components/layout/docs.js
  pages/docs/api/v1/index.js
  pages/docs/api/v2/index.js
  pages/docs/integrations/v2/index.js
Labels: automerge

#1101 Fix Snippet not sharing Toasts
  components/layout/layout.js
  components/snippet/snippet.js
Labels: automerge

#1102 Change terminalInput for snippet
  pages/guides/deploying-nuxtjs-with-now.mdx
Labels: automerge

#1104 Update Old Links
  pages/docs/v2/advanced/concepts/cdn-and-global-distribution.mdx
  pages/docs/v2/advanced/concepts/immutability.mdx
  pages/docs/v2/advanced/concepts/lambdas.mdx
  pages/docs/v2/advanced/concepts/lifecycle.mdx
  pages/docs/v2/advanced/concepts/overview.mdx
  pages/docs/v2/advanced/concepts/special-paths.mdx
  pages/docs/v2/advanced/concepts/urls.mdx
  pages/docs/v2/advanced/configuration.mdx
  pages/docs/v2/advanced/deploy-hooks.mdx
  pages/docs/v2/advanced/domains/transferring-a-domain.mdx
  pages/docs/v2/advanced/now-for-github.mdx
  pages/docs/v2/advanced/now-for-gitlab.mdx
  pages/docs/v2/advanced/platform/changes-in-now-2-0.mdx
  pages/docs/v2/advanced/platform/projects.mdx
  pages/docs/v2/advanced/platform/regions-and-providers.mdx
  pages/docs/v2/advanced/routes.mdx
  pages/docs/v2/network/caching.mdx
  pages/docs/v2/network/headers.mdx
  pages/docs/v2/network/overview.mdx
  pages/docs/v2/network/status-codes.mdx
  pages/guides/deploying-sanity-studio-with-now.mdx
Labels: automerge

#1105 Link Fixes
  pages/docs/v2/advanced/builders.mdx
  pages/docs/v2/advanced/concepts/lifecycle.mdx
  pages/docs/v2/advanced/concepts/special-paths.mdx
  pages/docs/v2/advanced/configuration.mdx
  pages/docs/v2/advanced/global-configuration.mdx
  pages/docs/v2/advanced/platform/changes-in-now-2-0.mdx
  pages/docs/v2/advanced/platform/projects.mdx
  pages/docs/v2/advanced/routes.mdx
  pages/docs/v2/environment-variables-and-secrets.mdx
  pages/docs/v2/network/headers.mdx
  pages/guides/deploying-a-mongodb-powered-api-with-node-and-now.mdx
  pages/guides/deploying-next-and-mysql-with-now.mdx
  pages/guides/handling-node-request-body.mdx
  pages/guides/redirect-from-www.mdx
  pages/guides/setup-godaddy-domain-now.mdx
  pages/guides/setup-namecheap-domain-now.mdx
  pages/guides/zero-downtime-domain-migration.mdx
Labels: automerge

#1106 Remove Resources Section
  components/snippet/snippet.js
  pages/docs/v1/features/cdn.mdx
  pages/docs/v1/other/faq.mdx
  pages/guides/custom-next-js-server-to-routes.mdx
  pages/guides/deploying-a-mongodb-powered-api-with-node-and-now.mdx
  pages/guides/deploying-angular-with-now.mdx
  pages/guides/deploying-apolloserver-to-now.mdx
  pages/guides/deploying-charge-with-now.mdx
  pages/guides/deploying-gatsby-with-now.mdx
  pages/guides/deploying-hugo-with-now.mdx
  pages/guides/deploying-next-and-buttercms-with-now.mdx
  pages/guides/deploying-next-and-contentful-with-now.mdx
  pages/guides/deploying-next-and-mysql-with-now.mdx
  pages/guides/deploying-next-and-prismic-with-now.mdx
  pages/guides/deploying-next-and-storyblok-with-now.mdx
  pages/guides/deploying-nextjs-with-now.mdx
  pages/guides/deploying-nuxtjs-with-now.mdx
  pages/guides/deploying-react-with-now-cra.mdx
  pages/guides/deploying-sanity-studio-with-now.mdx
  pages/guides/deploying-vuejs-to-now.mdx
  pages/guides/deploying-vuepress-to-now.mdx
  pages/guides/getting-started-with-now-for-gitlab.mdx
  pages/guides/handling-node-request-body.mdx
  pages/guides/setup-godaddy-domain-now.mdx
  pages/guides/setup-namecheap-domain-now.mdx
  pages/guides/updating-now-cli.mdx
  pages/guides/zero-downtime-domain-migration.mdx
Labels: automerge

#1109 Update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#1108 Add a Community Builders section
  pages/docs/v2/advanced/builders.mdx
Labels: automerge

#1100 Link to `single deployment`
  pages/docs/api/v2/api-docs-mdx/endpoints/deployments.mdx
Labels: automerge

#1111 Fix sidebar scroll behaviour
  components/layout/content.js
  components/layout/sidebar.js
Labels: automerge

#1113 Update menu-toggle icon to match front
  components/layout/header/header-wrapper.js
  components/layout/header/header.js
  components/layout/header/menu-toggle.js
Labels: automerge

#1116 Fix sidebar scroll behaviour (WIP)
  components/layout/content.js
  components/layout/docs.js
  components/layout/layout.js
  components/layout/sidebar.js
  pages/docs/api/v1/index.js
  pages/docs/api/v2/index.js
  pages/docs/integrations/v2/index.js
Labels: In Progress, automerge

#1146 [guides] Use npm instead of yarn
  pages/guides/deploying-a-mongodb-powered-api-with-node-and-now.mdx
  pages/guides/deploying-angular-with-now.mdx
  pages/guides/deploying-apolloserver-to-now.mdx
  pages/guides/deploying-charge-with-now.mdx
  pages/guides/deploying-gatsby-with-now.mdx
  pages/guides/deploying-next-and-buttercms-with-now.mdx
  pages/guides/deploying-next-and-contentful-with-now.mdx
  pages/guides/deploying-next-and-mysql-with-now.mdx
  pages/guides/deploying-next-and-prismic-with-now.mdx
  pages/guides/deploying-next-and-storyblok-with-now.mdx
  pages/guides/deploying-nextjs-with-now.mdx
  pages/guides/deploying-nuxtjs-with-zeit-now.mdx
  pages/guides/deploying-preact-with-zeit-now.mdx
  pages/guides/deploying-react-with-now-cra.mdx
  pages/guides/deploying-sanity-studio-with-now.mdx
  pages/guides/deploying-vuejs-to-now.mdx
  pages/guides/deploying-vuepress-to-now.mdx
  pages/guides/upgrade-to-zero-configuration.mdx
Labels: Section: Guides

#1168 Remove Incorrect Routes Information
  pages/docs/v2/advanced/routes.mdx
Labels: In Progress

#1197 Add project domain related API docs
  pages/docs/api/v2/api-docs-mdx/endpoints/projects.mdx
Labels: important

#1222 Use npm Over npx for Introduction
  pages/docs/v2/introduction.mdx
Labels: Section: Docs

#1226 Update Deployment Command Phrasing
  pages/guides/custom-next-js-server-to-routes.mdx
  pages/guides/deploying-angular-with-now.mdx
  pages/guides/deploying-apolloserver-to-now.mdx
  pages/guides/deploying-charge-with-now.mdx
  pages/guides/deploying-gatsby-with-now.mdx
  pages/guides/deploying-gridsome-with-zeit-now.mdx
  pages/guides/deploying-hugo-with-now.mdx
  pages/guides/deploying-next-and-buttercms-with-now.mdx
  pages/guides/deploying-next-and-contentful-with-now.mdx
  pages/guides/deploying-next-and-mysql-with-now.mdx
  pages/guides/deploying-next-and-storyblok-with-now.mdx
  pages/guides/deploying-nuxtjs-with-zeit-now.mdx
  pages/guides/deploying-preact-with-zeit-now.mdx
  pages/guides/deploying-pusher-channels-with-zeit-now.mdx
  pages/guides/deploying-react-with-now-cra.mdx
  pages/guides/deploying-sanity-studio-with-now.mdx
  pages/guides/deploying-storybook-with-zeit-now.mdx
  pages/guides/deploying-vuejs-to-now.mdx
  pages/guides/deploying-vuepress-to-now.mdx
  pages/guides/handling-node-request-body.mdx
Labels: Section: Guides
