Repository vercel/docs, pull requests merged in 2019-01, with the labels that each got.

#390 Moved alias to a deeper level
  LICENSE.md
  README.md
  now.json
Labels: Type: Fix

#391 Deploy to multiple aliases for safety
  now.json
Labels: Type: Improvement

#403 Removed extra alias
  now.json
Labels: Type: Improvement

#412 Fixed chat counter
  components/chat-count/chat-count.js
  lib/data/last-edited.json
Labels: Type: Improvement

#417 Typo unavailabe
  pages/docs/api/v1/api-docs-mdx/errors/domains.mdx
  pages/docs/api/v2/api-docs-mdx/errors/domains.mdx
Labels: Section: API, good first issue
